### ISSUE TITLE
Pre-trained Weights are no longer available !! help please !! i need it

### ISSUE THREAD

**Issue by walido13** [soumik12345/MIRNet#7]
Hey i can't download pre-trained weight even yu provide a link of TFLite (mirnet-fixed/dr) but didn't work should have the pretrained model please help me i need this for my studies

**Comment by soumik12345** [comment]
Hi @walido13 
You can get the weights by training the model using [this](https://keras.io/examples/vision/mirnet/) notebook.

**Comment by walido13** [comment]
okey thank you bro
